title: Magni Documentation
description: Learn to use our robots with ROS
email: jrlandau@gmail.com


remote_theme: carlosperate/jekyll-theme-rtd

plugins:
- jekyll-remote-theme
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
